### ISSUE TITLE
get_subcuenta puede, en algunos casos, sobreescribir la descripción de una subcuenta existente.

### ISSUE THREAD

**Issue by cpba** [NeoRazorX/facturacion_base#98]
En caso de no encontrar ninguna subcuenta asignada a un proveedor, `get_subcuenta` de la clase proveedor llama `new_subcuenta` de la clase cuenta para obtener y asignar una cuenta nueva.

Sin embargo en caso de que ya exista una subcuenta terminada en las mismas cifras que el código de proveedor, `new_subcuenta` devuelve la subcuenta preexistente en lugar de crear una nueva, acto seguido `get_subcuenta` sobrescribe la descripción con la razón social del nuevo proveedor.

Este comportamiento nos perjudica cuando introducimos datos desde un plan contable anterior, puesto que hace necesario comprobar y reescribir la descripción de las subcuentas ya creadas cuando el código autogenerado de un nuevo proveedor coincide con el numero de uno de ellas.

La solución que estamos usando internamente consiste simplemente en comprobar que `subcuenta->descripcion` esté vació antes de substituir su contenido con el de `proveedor->razonsocial`.

Si crees que es una buena idea te lo voy a mandar como pull request.

Sin embargo entiendo que puedas considerar esta solución un tanto sucia, así que estoy abierto a sugerencias sobre como proceder.

**Comment by NeoRazorX** [comment]
Me vale. Envía los cambios ;-)

**Comment by cpba** [comment]
Aqui lo tienes, como decia es un poco sucio:
https://github.com/NeoRazorX/facturacion_base/pull/100
